// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/bsos.proto

package bsospb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           uint64                 `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`                              // client-computed xxh3_64(content); server trusts it, never verifies
	TotalSize     uint64                 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // required; must arrive before any data chunk
	AliasFor      uint64                 `protobuf:"varint,3,opt,name=alias_for,json=aliasFor,proto3" json:"alias_for,omitempty"`    // optional, 0 = normal put. Non-zero: also register
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutHeader) Reset() {
	*x = PutHeader{}
	mi := &file_proto_bsos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutHeader) ProtoMessage() {}

func (x *PutHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bsos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutHeader.ProtoReflect.Descriptor instead.
func (*PutHeader) Descriptor() ([]byte, []int) {
	return file_proto_bsos_proto_rawDescGZIP(), []int{0}
}

func (x *PutHeader) GetFid() uint64 {
	if x != nil {
		return x.Fid
	}
	return 0
}

func (x *PutHeader) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *PutHeader) GetAliasFor() uint64 {
	if x != nil {
		return x.AliasFor
	}
	return 0
}

type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PutRequest_Header
	//	*PutRequest_Chunk
	Msg           isPutRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_bsos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bsos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_bsos_proto_rawDescGZIP(), []int{1}
}

func (x *PutRequest) GetMsg() isPutRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PutRequest) GetHeader() *PutHeader {
	if x != nil {
		if x, ok := x.Msg.(*PutRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *PutRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Msg.(*PutRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isPutRequest_Msg interface {
	isPutRequest_Msg()
}

type PutRequest_Header struct {
	Header *PutHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"` // must be the first message on the stream
}

type PutRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // subsequent messages, streamed straight to disk
}

func (*PutRequest_Header) isPutRequest_Msg() {}

func (*PutRequest_Chunk) isPutRequest_Msg() {}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_bsos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bsos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_bsos_proto_rawDescGZIP(), []int{2}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           uint64                 `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	HasRange      bool                   `protobuf:"varint,2,opt,name=has_range,json=hasRange,proto3" json:"has_range,omitempty"`
	RangeStart    uint64                 `protobuf:"varint,3,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	RangeEnd      uint64                 `protobuf:"varint,4,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_bsos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bsos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_bsos_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetFid() uint64 {
	if x != nil {
		return x.Fid
	}
	return 0
}

func (x *GetRequest) GetHasRange() bool {
	if x != nil {
		return x.HasRange
	}
	return false
}

func (x *GetRequest) GetRangeStart() uint64 {
	if x != nil {
		return x.RangeStart
	}
	return 0
}

func (x *GetRequest) GetRangeEnd() uint64 {
	if x != nil {
		return x.RangeEnd
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	RangeStart    uint64                 `protobuf:"varint,2,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	RangeEnd      uint64                 `protobuf:"varint,3,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_bsos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bsos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_bsos_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetResponse) GetRangeStart() uint64 {
	if x != nil {
		return x.RangeStart
	}
	return 0
}

func (x *GetResponse) GetRangeEnd() uint64 {
	if x != nil {
		return x.RangeEnd
	}
	return 0
}

func (x *GetResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           uint64                 `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadRequest) Reset() {
	*x = HeadRequest{}
	mi := &file_proto_bsos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadRequest) ProtoMessage() {}

func (x *HeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bsos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadRequest.ProtoReflect.Descriptor instead.
func (*HeadRequest) Descriptor() ([]byte, []int) {
	return file_proto_bsos_proto_rawDescGZIP(), []int{5}
}

func (x *HeadRequest) GetFid() uint64 {
	if x != nil {
		return x.Fid
	}
	return 0
}

type HeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadResponse) Reset() {
	*x = HeadResponse{}
	mi := &file_proto_bsos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadResponse) ProtoMessage() {}

func (x *HeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bsos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadResponse.ProtoReflect.Descriptor instead.
func (*HeadResponse) Descriptor() ([]byte, []int) {
	return file_proto_bsos_proto_rawDescGZIP(), []int{6}
}

func (x *HeadResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_bsos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bsos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_bsos_proto_rawDescGZIP(), []int{7}
}

type BonnieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChDPow2       uint32                 `protobuf:"varint,1,opt,name=ch_d_pow2,json=chDPow2,proto3" json:"ch_d_pow2,omitempty"` // largest object size placeable with the
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BonnieResponse) Reset() {
	*x = BonnieResponse{}
	mi := &file_proto_bsos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BonnieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BonnieResponse) ProtoMessage() {}

func (x *BonnieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bsos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BonnieResponse.ProtoReflect.Descriptor instead.
func (*BonnieResponse) Descriptor() ([]byte, []int) {
	return file_proto_bsos_proto_rawDescGZIP(), []int{8}
}

func (x *BonnieResponse) GetChDPow2() uint32 {
	if x != nil {
		return x.ChDPow2
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_bsos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bsos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_bsos_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_bsos_proto protoreflect.FileDescriptor

const file_proto_bsos_proto_rawDesc = "" +
	"\n" +
	"\x10proto/bsos.proto\x12\x04bsos\"Y\n" +
	"\tPutHeader\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\x04R\x03fid\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\x12\x1b\n" +
	"\talias_for\x18\x03 \x01(\x04R\baliasFor\"V\n" +
	"\n" +
	"PutRequest\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x0f.bsos.PutHeaderH\x00R\x06header\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x05\n" +
	"\x03msg\"\r\n" +
	"\vPutResponse\"y\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\x04R\x03fid\x12\x1b\n" +
	"\thas_range\x18\x02 \x01(\bR\bhasRange\x12\x1f\n" +
	"\vrange_start\x18\x03 \x01(\x04R\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x04 \x01(\x04R\brangeEnd\"s\n" +
	"\vGetResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x12\x1f\n" +
	"\vrange_start\x18\x02 \x01(\x04R\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x03 \x01(\x04R\brangeEnd\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x1f\n" +
	"\vHeadRequest\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\x04R\x03fid\"\"\n" +
	"\fHeadResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\"\a\n" +
	"\x05Empty\",\n" +
	"\x0eBonnieResponse\x12\x1a\n" +
	"\tch_d_pow2\x18\x01 \x01(\rR\achDPow2\" \n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xeb\x01\n" +
	"\x04BSOS\x12,\n" +
	"\x03Put\x12\x10.bsos.PutRequest\x1a\x11.bsos.PutResponse(\x01\x12,\n" +
	"\x03Get\x12\x10.bsos.GetRequest\x1a\x11.bsos.GetResponse0\x01\x12-\n" +
	"\x04Head\x12\x11.bsos.HeadRequest\x1a\x12.bsos.HeadResponse\x12+\n" +
	"\x06Bonnie\x12\v.bsos.Empty\x1a\x14.bsos.BonnieResponse\x12+\n" +
	"\x06Health\x12\v.bsos.Empty\x1a\x14.bsos.HealthResponseB\x1dZ\x1bbsos/internal/daemon/bsospbb\x06proto3"

var (
	file_proto_bsos_proto_rawDescOnce sync.Once
	file_proto_bsos_proto_rawDescData []byte
)

func file_proto_bsos_proto_rawDescGZIP() []byte {
	file_proto_bsos_proto_rawDescOnce.Do(func() {
		file_proto_bsos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bsos_proto_rawDesc), len(file_proto_bsos_proto_rawDesc)))
	})
	return file_proto_bsos_proto_rawDescData
}

var file_proto_bsos_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_bsos_proto_goTypes = []any{
	(*PutHeader)(nil),      // 0: bsos.PutHeader
	(*PutRequest)(nil),     // 1: bsos.PutRequest
	(*PutResponse)(nil),    // 2: bsos.PutResponse
	(*GetRequest)(nil),     // 3: bsos.GetRequest
	(*GetResponse)(nil),    // 4: bsos.GetResponse
	(*HeadRequest)(nil),    // 5: bsos.HeadRequest
	(*HeadResponse)(nil),   // 6: bsos.HeadResponse
	(*Empty)(nil),          // 7: bsos.Empty
	(*BonnieResponse)(nil), // 8: bsos.BonnieResponse
	(*HealthResponse)(nil), // 9: bsos.HealthResponse
}
var file_proto_bsos_proto_depIdxs = []int32{
	0, // 0: bsos.PutRequest.header:type_name -> bsos.PutHeader
	1, // 1: bsos.BSOS.Put:input_type -> bsos.PutRequest
	3, // 2: bsos.BSOS.Get:input_type -> bsos.GetRequest
	5, // 3: bsos.BSOS.Head:input_type -> bsos.HeadRequest
	7, // 4: bsos.BSOS.Bonnie:input_type -> bsos.Empty
	7, // 5: bsos.BSOS.Health:input_type -> bsos.Empty
	2, // 6: bsos.BSOS.Put:output_type -> bsos.PutResponse
	4, // 7: bsos.BSOS.Get:output_type -> bsos.GetResponse
	6, // 8: bsos.BSOS.Head:output_type -> bsos.HeadResponse
	8, // 9: bsos.BSOS.Bonnie:output_type -> bsos.BonnieResponse
	9, // 10: bsos.BSOS.Health:output_type -> bsos.HealthResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bsos_proto_init() }
func file_proto_bsos_proto_init() {
	if File_proto_bsos_proto != nil {
		return
	}
	file_proto_bsos_proto_msgTypes[1].OneofWrappers = []any{
		(*PutRequest_Header)(nil),
		(*PutRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bsos_proto_rawDesc), len(file_proto_bsos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bsos_proto_goTypes,
		DependencyIndexes: file_proto_bsos_proto_depIdxs,
		MessageInfos:      file_proto_bsos_proto_msgTypes,
	}.Build()
	File_proto_bsos_proto = out.File
	file_proto_bsos_proto_goTypes = nil
	file_proto_bsos_proto_depIdxs = nil
}
