// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/bsos.proto

package bsospb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BSOS_Put_FullMethodName    = "/bsos.BSOS/Put"
	BSOS_Get_FullMethodName    = "/bsos.BSOS/Get"
	BSOS_Head_FullMethodName   = "/bsos.BSOS/Head"
	BSOS_Bonnie_FullMethodName = "/bsos.BSOS/Bonnie"
	BSOS_Health_FullMethodName = "/bsos.BSOS/Health"
)

// BSOSClient is the client API for BSOS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BSOSClient interface {
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, PutResponse], error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error)
	Head(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (*HeadResponse, error)
	Bonnie(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BonnieResponse, error)
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type bSOSClient struct {
	cc grpc.ClientConnInterface
}

func NewBSOSClient(cc grpc.ClientConnInterface) BSOSClient {
	return &bSOSClient{cc}
}

func (c *bSOSClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, PutResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BSOS_ServiceDesc.Streams[0], BSOS_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutRequest, PutResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BSOS_PutClient = grpc.ClientStreamingClient[PutRequest, PutResponse]

func (c *bSOSClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BSOS_ServiceDesc.Streams[1], BSOS_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BSOS_GetClient = grpc.ServerStreamingClient[GetResponse]

func (c *bSOSClient) Head(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (*HeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeadResponse)
	err := c.cc.Invoke(ctx, BSOS_Head_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bSOSClient) Bonnie(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BonnieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BonnieResponse)
	err := c.cc.Invoke(ctx, BSOS_Bonnie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bSOSClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BSOS_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BSOSServer is the server API for BSOS service.
// All implementations must embed UnimplementedBSOSServer
// for forward compatibility.
type BSOSServer interface {
	Put(grpc.ClientStreamingServer[PutRequest, PutResponse]) error
	Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error
	Head(context.Context, *HeadRequest) (*HeadResponse, error)
	Bonnie(context.Context, *Empty) (*BonnieResponse, error)
	Health(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedBSOSServer()
}

// UnimplementedBSOSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBSOSServer struct{}

func (UnimplementedBSOSServer) Put(grpc.ClientStreamingServer[PutRequest, PutResponse]) error {
	return status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedBSOSServer) Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBSOSServer) Head(context.Context, *HeadRequest) (*HeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Head not implemented")
}
func (UnimplementedBSOSServer) Bonnie(context.Context, *Empty) (*BonnieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bonnie not implemented")
}
func (UnimplementedBSOSServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBSOSServer) mustEmbedUnimplementedBSOSServer() {}
func (UnimplementedBSOSServer) testEmbeddedByValue()              {}

// UnsafeBSOSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BSOSServer will
// result in compilation errors.
type UnsafeBSOSServer interface {
	mustEmbedUnimplementedBSOSServer()
}

func RegisterBSOSServer(s grpc.ServiceRegistrar, srv BSOSServer) {
	// If the following call panics, it indicates UnimplementedBSOSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BSOS_ServiceDesc, srv)
}

func _BSOS_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BSOSServer).Put(&grpc.GenericServerStream[PutRequest, PutResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BSOS_PutServer = grpc.ClientStreamingServer[PutRequest, PutResponse]

func _BSOS_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BSOSServer).Get(m, &grpc.GenericServerStream[GetRequest, GetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BSOS_GetServer = grpc.ServerStreamingServer[GetResponse]

func _BSOS_Head_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BSOSServer).Head(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BSOS_Head_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BSOSServer).Head(ctx, req.(*HeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BSOS_Bonnie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BSOSServer).Bonnie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BSOS_Bonnie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BSOSServer).Bonnie(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BSOS_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BSOSServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BSOS_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BSOSServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BSOS_ServiceDesc is the grpc.ServiceDesc for BSOS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BSOS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bsos.BSOS",
	HandlerType: (*BSOSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Head",
			Handler:    _BSOS_Head_Handler,
		},
		{
			MethodName: "Bonnie",
			Handler:    _BSOS_Bonnie_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _BSOS_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _BSOS_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _BSOS_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/bsos.proto",
}
